name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: "deps"
        run: apk add doas
      - uses: extractions/setup-just@v2
      - name: "iso"
        run: cd configs/iso && ./configure deps
      - name: "iso"
        run: cd configs/apkovl && ./configure
