name: "build"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  neovim:
    runs-on: ubuntu-24.04-arm
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: "clone root"
        uses: docker://alpine:latest
        run: cd package/neovim && ./configure
      - name: "artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: neovim-data
          path: |
            package/neovim/nvim-*.tar.gz
